const plugin = require("tailwindcss/plugin");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: ["class", "class"],
  theme: {
    extend: {
      colors: {
        background: "var(--color-sky-tint)",
        surface: "var(--color-bone-white)",
        "surface-elevated": "var(--color-paper-white)",
        "surface-glass": "rgba(235, 245, 255, 0.85)",
        foreground: "var(--color-ink)",
        muted: "var(--color-fog)",
        border: "transparent",
        
        /* NexTradeX Design Tokens */
        "sky-tint": "#ebf5ff",
        "paper-white": "#ffffff",
        "bone-white": "#fafdff",
        "mist-gray": "#f6f7f8",
        ink: "#0a0d12",
        charcoal: "#181d27",
        graphite: "#535862",
        fog: "#93979f",
        "slate-shadow": "#3b3d41",
        "iris-blue": "#0069e0",
        "sky-blue": "#0099ff",
        "lavender-wash": "#f1e6ff",
        "mint-wash": "#d3f6e3",
        "powder-blue": "#cce7ff",
        "solar-gradient": "#fff2be",
        "violet-gradient": "#e4ccff",
        "aqua-gradient": "#c2e9ff",
        "peach-gradient": "#ffd1b8",
        
        primary: "#181d27",
        "primary-active": "#0a0d12",
        secondary: "#0069e0",
        "trading-up": "#13A978",
        "trading-down": "#E05263",
        "accent-turquoise": "#38B2AC",
        info: "#4F7DFF",
        "info-ring": "#6C63FF",
        "on-primary": "#FFFFFF",
        "on-dark": "#3D4852",
      },
      fontFamily: {
        aeonik: [
          '"Inter"',
          '"Plus Jakarta Sans"',
          "-apple-system",
          "BlinkMacSystemFont",
          "sans-serif",
        ],
        display: [
          '"Inter"',
          '"Plus Jakarta Sans"',
          "-apple-system",
          "BlinkMacSystemFont",
          "sans-serif",
        ],
        heading: [
          '"Inter"',
          '"Plus Jakarta Sans"',
          "-apple-system",
          "BlinkMacSystemFont",
          "sans-serif",
        ],
        geist: [
          '"Geist"',
          '"Inter"',
          "-apple-system",
          "BlinkMacSystemFont",
          "sans-serif",
        ],
        body: [
          '"Geist"',
          '"Inter"',
          "-apple-system",
          "BlinkMacSystemFont",
          "sans-serif",
        ],
        mono: ['"JetBrains Mono"', '"IBM Plex Mono"', "ui-monospace", "monospace"],
      },
      boxShadow: {
        "genie-cta": "0 1px 2px rgba(10, 13, 18, 0.8), 0 0 0 1px #0a0d12",
        "genie-lg": "rgba(4, 69, 144, 0.08) 0px 14px 20px 4px",
        "genie-subtle": "rgba(10, 13, 18, 0.06) 0px 4px 12px 0px",
        neo: "0 1px 2px rgba(10, 13, 18, 0.8), 0 0 0 1px #0a0d12",
        "neo-hover": "rgba(4, 69, 144, 0.08) 0px 14px 20px 4px",
        "neo-sm": "0 1px 2px rgba(10, 13, 18, 0.3), 0 0 0 1px rgba(10, 13, 18, 0.05)",
        "neo-inset": "inset 0 2px 4px rgba(10, 13, 18, 0.06)",
        "neo-inset-deep": "inset 0 4px 8px rgba(10, 13, 18, 0.08)",
        "neo-inset-sm": "inset 0 1px 2px rgba(10, 13, 18, 0.04)",
        "glow-primary": "0 0 15px rgba(0, 105, 224, 0.3)",
        "glow-soft": "0 0 10px rgba(0, 105, 224, 0.15)",
        "elevation-sm": "0 2px 4px rgba(10, 13, 18, 0.04)",
        "elevation-md": "0 4px 12px rgba(10, 13, 18, 0.06)",
        "elevation-lg": "rgba(4, 69, 144, 0.08) 0px 14px 20px 4px",
        "inner-glow": "inset 0 0 10px rgba(0, 105, 224, 0.1)",
      },
      borderRadius: {
        tags: "9999px",
        cards: "32px",
        images: "24px",
        inputs: "16px",
        buttons: "32px",
        cardsSmall: "16px",
        buttonsPill: "9999px",
        "3xl": "32px",
        pill: "9999px",
      },
      spacing: {
        8: "8px",
        16: "16px",
        24: "24px",
        32: "32px",
        40: "40px",
        48: "48px",
        56: "56px",
        64: "64px",
        80: "80px",
        88: "88px",
        120: "120px",
        160: "160px",
      },
      animation: {
        float: "float 3s ease-in-out infinite",
        "float-slow": "float 6s ease-in-out infinite",
        "slide-down": "slideDown 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "slide-up": "slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "fade-in": "fadeIn 0.3s cubic-bezier(0.4, 0, 0.2, 1) forwards",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
    },
  },
  plugins: [
    plugin(function ({ addVariant }) {
      addVariant("light", ".light &");
    }),
  ],
};

