-- Apply once to an existing PostgreSQL database before deploying this release.
BEGIN;

ALTER TABLE wallets ADD COLUMN IF NOT EXISTS version BIGINT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS version BIGINT;
ALTER TABLE futures_positions ADD COLUMN IF NOT EXISTS version BIGINT;
ALTER TABLE margin_positions ADD COLUMN IF NOT EXISTS version BIGINT;
ALTER TABLE options_contracts ADD COLUMN IF NOT EXISTS version BIGINT;

UPDATE wallets SET version = 0 WHERE version IS NULL;
UPDATE orders SET version = 0 WHERE version IS NULL;
UPDATE futures_positions SET version = 0 WHERE version IS NULL;
UPDATE margin_positions SET version = 0 WHERE version IS NULL;
UPDATE options_contracts SET version = 0 WHERE version IS NULL;

ALTER TABLE wallets ALTER COLUMN version SET DEFAULT 0;
ALTER TABLE wallets ALTER COLUMN version SET NOT NULL;
ALTER TABLE orders ALTER COLUMN version SET DEFAULT 0;
ALTER TABLE orders ALTER COLUMN version SET NOT NULL;
ALTER TABLE futures_positions ALTER COLUMN version SET DEFAULT 0;
ALTER TABLE futures_positions ALTER COLUMN version SET NOT NULL;
ALTER TABLE margin_positions ALTER COLUMN version SET DEFAULT 0;
ALTER TABLE margin_positions ALTER COLUMN version SET NOT NULL;
ALTER TABLE options_contracts ALTER COLUMN version SET DEFAULT 0;
ALTER TABLE options_contracts ALTER COLUMN version SET NOT NULL;

DROP INDEX IF EXISTS idx_margin_user_symbol;
CREATE INDEX IF NOT EXISTS idx_margin_user_symbol
    ON margin_positions (user_id, symbol);

CREATE TABLE IF NOT EXISTS spot_holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL REFERENCES users (id),
    asset VARCHAR(16) NOT NULL,
    quantity NUMERIC(19, 8) NOT NULL DEFAULT 0,
    average_entry_price NUMERIC(19, 8) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_spot_holding_user_asset UNIQUE (user_id, asset),
    CONSTRAINT ck_spot_holding_quantity_nonnegative CHECK (quantity >= 0)
);

CREATE INDEX IF NOT EXISTS idx_spot_holding_user
    ON spot_holdings (user_id);

DO $$
DECLARE
    trade RECORD;
    base_asset VARCHAR(16);
BEGIN
    IF NOT EXISTS (SELECT 1 FROM spot_holdings) THEN
        FOR trade IN
            SELECT user_id, symbol, side, quantity, execution_price
            FROM spot_trades
            WHERE UPPER(symbol) ~ '^[A-Z0-9]+(USDT|USDC|BUSD)$'
            ORDER BY created_at, id
        LOOP
            base_asset := REGEXP_REPLACE(
                    UPPER(trade.symbol), '(USDT|USDC|BUSD)$', '');

            IF UPPER(trade.side) = 'BUY' THEN
                INSERT INTO spot_holdings (
                    user_id, asset, quantity, average_entry_price)
                VALUES (
                    trade.user_id, base_asset, trade.quantity,
                    trade.execution_price)
                ON CONFLICT (user_id, asset) DO UPDATE
                SET average_entry_price =
                        ((spot_holdings.average_entry_price * spot_holdings.quantity)
                        + (EXCLUDED.average_entry_price * EXCLUDED.quantity))
                        / (spot_holdings.quantity + EXCLUDED.quantity),
                    quantity = spot_holdings.quantity + EXCLUDED.quantity,
                    updated_at = CURRENT_TIMESTAMP,
                    version = spot_holdings.version + 1;
            ELSIF UPPER(trade.side) = 'SELL' THEN
                UPDATE spot_holdings
                SET quantity = GREATEST(quantity - trade.quantity, 0),
                    average_entry_price = CASE
                        WHEN quantity - trade.quantity <= 0 THEN 0
                        ELSE average_entry_price
                    END,
                    updated_at = CURRENT_TIMESTAMP,
                    version = version + 1
                WHERE user_id = trade.user_id
                  AND asset = base_asset;
            END IF;
        END LOOP;
    END IF;
END $$;

COMMIT;
