import {
  TradeUpIcon,
  FlashIcon,
  BotIcon,
  MoneyExchange01Icon,
  UserGroupIcon,
  StarsIcon,
  Activity01Icon,
  CoinsDollarIcon,
  Coins01Icon,
  MarketAnalysisIcon,
  GiftIcon,
  Book01Icon,
  Layers01Icon,
  Globe02Icon,
} from "@hugeicons/core-free-icons";

/**
 * Navbar Mega Menu Configuration Data
 * Pure NexTradeX branded menu options with Hugeicons stroke-rounded crypto icons.
 */

export const TRADE_MENU_DATA = {
  header: {
    title: "Trade",
    description: "Be the first to capture high quality on-chain assets.",
  },
  items: [
    {
      id: "spot",
      title: "Spot Trading",
      description: "Trade crypto with comprehensive tools",
      icon: TradeUpIcon,
      route: "/trade/spot",
      badge: null,
    },
    {
      id: "margin",
      title: "Margin Trading",
      description: "Magnify profits with leverage",
      icon: FlashIcon,
      route: "/trade/margin",
      badge: null,
    },
    {
      id: "bot",
      title: "Trading Bot",
      description: "Automate your trades with algorithmic help",
      icon: BotIcon,
      route: "/trade/bot",
      badge: null,
    },
    {
      id: "convert",
      title: "Convert",
      description: "The easiest way to trade",
      icon: MoneyExchange01Icon,
      route: "/trade/convert",
      badge: null,
    },
    {
      id: "copy",
      title: "Copy Trading",
      description: "Grow your profits with top traders",
      icon: UserGroupIcon,
      route: "/trade/copy",
      badge: null,
    },
    {
      id: "alpha",
      title: "NexTradeX Alpha",
      description: "Capture early on-chain opportunities",
      icon: StarsIcon,
      route: "/trade/alpha",
      badge: "NEW",
    },
  ],
  marketPanel: {
    tabs: ["Majors", "New", "TON", "More"],
    assets: {
      Majors: [
        { symbol: "BTC", name: "Bitcoin", price: "$63,812.70", change: "+1.61%", positive: true },
        { symbol: "ETH", name: "Ethereum", price: "$1,858.00", change: "+0.70%", positive: true },
        { symbol: "SOL", name: "Solana", price: "$143.40", change: "+1.11%", positive: true },
        { symbol: "BNB", name: "BNB Chain", price: "$591.70", change: "+1.04%", positive: true },
        { symbol: "XRP", name: "XRP Ledger", price: "$1.0750", change: "+0.58%", positive: true },
        { symbol: "ADA", name: "Cardano", price: "$0.3930", change: "+2.22%", positive: true },
        { symbol: "AVAX", name: "Avalanche", price: "$24.85", change: "+3.42%", positive: true },
        { symbol: "DOT", name: "Polkadot", price: "$4.85", change: "+0.85%", positive: true },
        { symbol: "LINK", name: "Chainlink", price: "$11.27", change: "-0.14%", positive: false },
        { symbol: "LTC", name: "Litecoin", price: "$65.40", change: "+0.45%", positive: true },
        { symbol: "BCH", name: "Bitcoin Cash", price: "$345.20", change: "+1.20%", positive: true },
        { symbol: "NTX", name: "NexTradeX Token", price: "$10.45", change: "+0.95%", positive: true },
      ],
      New: [
        { symbol: "PEPE", name: "Pepe Coin", price: "$0.00000890", change: "+5.88%", positive: true },
        { symbol: "WIF", name: "dogwifhat", price: "$1.8400", change: "+4.53%", positive: true },
        { symbol: "SUI", name: "Sui Network", price: "$1.6400", change: "+5.20%", positive: true },
        { symbol: "SHIB", name: "Shiba Inu", price: "$0.0000178", change: "+2.15%", positive: true },
        { symbol: "BONK", name: "Bonk", price: "$0.0000214", change: "+3.80%", positive: true },
        { symbol: "FLOKI", name: "Floki", price: "$0.000142", change: "+1.90%", positive: true },
        { symbol: "TIA", name: "Celestia", price: "$5.1800", change: "+4.10%", positive: true },
        { symbol: "SEI", name: "Sei Network", price: "$0.3800", change: "+3.50%", positive: true },
        { symbol: "ARB", name: "Arbitrum", price: "$0.5400", change: "+1.80%", positive: true },
        { symbol: "OP", name: "Optimism", price: "$1.4200", change: "+2.30%", positive: true },
        { symbol: "FET", name: "Fetch.ai", price: "$1.3400", change: "+6.40%", positive: true },
        { symbol: "RENDER", name: "Render", price: "$5.4500", change: "+4.80%", positive: true },
      ],
      TON: [
        { symbol: "TON", name: "Toncoin", price: "$5.2400", change: "+1.85%", positive: true },
        { symbol: "NOT", name: "Notcoin", price: "$0.00840", change: "+6.10%", positive: true },
        { symbol: "DOGS", name: "Dogs Token", price: "$0.00062", change: "+3.15%", positive: true },
        { symbol: "HMSTR", name: "Hamster Kombat", price: "$0.00340", change: "+4.20%", positive: true },
        { symbol: "CATI", name: "Catizen", price: "$0.4200", change: "+5.10%", positive: true },
        { symbol: "MYRO", name: "Myro", price: "$0.0820", change: "+2.90%", positive: true },
      ],
      More: [
        { symbol: "NEAR", name: "NEAR Protocol", price: "$4.3200", change: "+2.10%", positive: true },
        { symbol: "APT", name: "Aptos", price: "$8.4500", change: "+3.10%", positive: true },
        { symbol: "ATOM", name: "Cosmos", price: "$5.1200", change: "+0.92%", positive: true },
        { symbol: "ICP", name: "Internet Computer", price: "$8.1000", change: "+1.45%", positive: true },
        { symbol: "UNI", name: "Uniswap", price: "$6.8500", change: "+2.40%", positive: true },
        { symbol: "INJ", name: "Injective", price: "$18.500", change: "+2.90%", positive: true },
        { symbol: "TRX", name: "TRON", price: "$0.1580", change: "+0.65%", positive: true },
        { symbol: "MATIC", name: "Polygon", price: "$0.4200", change: "+1.15%", positive: true },
        { symbol: "DOGE", name: "Dogecoin", price: "$0.1020", change: "+1.41%", positive: true },
        { symbol: "AAVE", name: "Aave", price: "$142.50", change: "+3.10%", positive: true },
        { symbol: "ALGO", name: "Algorand", price: "$0.1450", change: "+1.25%", positive: true },
        { symbol: "STX", name: "Stacks", price: "$1.8500", change: "+2.70%", positive: true },
      ],
    },
  },
};

export const DERIVATIVES_MENU_DATA = {
  header: {
    title: "Futures",
    description: "Browse all crypto derivatives",
  },
  items: [
    {
      id: "overview",
      title: "Futures Overview",
      description: "Browse all crypto derivatives",
      icon: Activity01Icon,
      route: "/trade/futures",
      badge: null,
    },
    {
      id: "usd-m",
      title: "USDS-Margined Futures",
      description: "USDS-settled linear contracts",
      icon: CoinsDollarIcon,
      route: "/trade/futures/usds",
      badge: null,
    },
    {
      id: "coin-m",
      title: "Coin-Margined Futures",
      description: "Coin-settled inverse contracts",
      icon: Coins01Icon,
      route: "/trade/futures/coin",
      badge: null,
    },
    {
      id: "stock-index",
      title: "Stock Index Perps",
      description: "Access and trade key global indices",
      icon: MarketAnalysisIcon,
      route: "/trade/futures/stock-index",
      badge: "HOT",
    },
    {
      id: "perks",
      title: "Futures Perks",
      description: "Discover exciting events and exclusive perks",
      icon: GiftIcon,
      route: "/trade/futures/perks",
      badge: null,
    },
  ],
  marketPanel: {
    tabs: ["ALL", "USDT-m", "USDC-m"],
    contracts: {
      ALL: [
        { symbol: "BTCUSDT", type: "Perp", price: "63,812.7", change: "+1.61%", positive: true },
        { symbol: "ETHUSDT", type: "Perp", price: "1,858.0", change: "+0.70%", positive: true },
        { symbol: "SOLUSDT", type: "Perp", price: "143.4", change: "+1.11%", positive: true },
        { symbol: "BNBUSDT", type: "Perp", price: "591.7", change: "+1.04%", positive: true },
        { symbol: "XRPUSDT", type: "Perp", price: "1.075", change: "+0.58%", positive: true },
        { symbol: "DOGEUSDT", type: "Perp", price: "0.102", change: "+1.41%", positive: true },
        { symbol: "PEPEUSDT", type: "Perp", price: "0.0000089", change: "+5.88%", positive: true },
        { symbol: "WIFUSDT", type: "Perp", price: "1.84", change: "+4.53%", positive: true },
        { symbol: "SHIBUSDT", type: "Perp", price: "0.0000178", change: "+2.15%", positive: true },
        { symbol: "SUIUSDT", type: "Perp", price: "1.64", change: "+5.20%", positive: true },
        { symbol: "AVAXUSDT", type: "Perp", price: "24.85", change: "+3.42%", positive: true },
        { symbol: "NEARUSDT", type: "Perp", price: "4.32", change: "+2.10%", positive: true },
        { symbol: "ARBUSDT", type: "Perp", price: "0.54", change: "+1.80%", positive: true },
        { symbol: "OPUSDT", type: "Perp", price: "1.42", change: "+2.30%", positive: true },
        { symbol: "TIAUSDT", type: "Perp", price: "5.18", change: "+4.10%", positive: true },
        { symbol: "SEIUSDT", type: "Perp", price: "0.38", change: "+3.50%", positive: true },
        { symbol: "FETUSDT", type: "Perp", price: "1.34", change: "+6.40%", positive: true },
        { symbol: "RENDERUSDT", type: "Perp", price: "5.45", change: "+4.80%", positive: true },
        { symbol: "TONUSDT", type: "Perp", price: "5.24", change: "+1.85%", positive: true },
        { symbol: "LINKUSDT", type: "Perp", price: "11.27", change: "-0.14%", positive: false },
      ],
      "USDT-m": [
        { symbol: "BTCUSDT", type: "Perp", price: "63,812.7", change: "+1.61%", positive: true },
        { symbol: "ETHUSDT", type: "Perp", price: "1,858.0", change: "+0.70%", positive: true },
        { symbol: "SOLUSDT", type: "Perp", price: "143.4", change: "+1.11%", positive: true },
        { symbol: "BNBUSDT", type: "Perp", price: "591.7", change: "+1.04%", positive: true },
        { symbol: "XRPUSDT", type: "Perp", price: "1.075", change: "+0.58%", positive: true },
        { symbol: "DOGEUSDT", type: "Perp", price: "0.102", change: "+1.41%", positive: true },
        { symbol: "PEPEUSDT", type: "Perp", price: "0.0000089", change: "+5.88%", positive: true },
        { symbol: "WIFUSDT", type: "Perp", price: "1.84", change: "+4.53%", positive: true },
        { symbol: "SHIBUSDT", type: "Perp", price: "0.0000178", change: "+2.15%", positive: true },
        { symbol: "SUIUSDT", type: "Perp", price: "1.64", change: "+5.20%", positive: true },
        { symbol: "AVAXUSDT", type: "Perp", price: "24.85", change: "+3.42%", positive: true },
        { symbol: "NEARUSDT", type: "Perp", price: "4.32", change: "+2.10%", positive: true },
        { symbol: "ARBUSDT", type: "Perp", price: "0.54", change: "+1.80%", positive: true },
        { symbol: "OPUSDT", type: "Perp", price: "1.42", change: "+2.30%", positive: true },
        { symbol: "TIAUSDT", type: "Perp", price: "5.18", change: "+4.10%", positive: true },
      ],
      "USDC-m": [
        { symbol: "BTCPERP", type: "Perp", price: "63,850.0", change: "+1.65%", positive: true },
        { symbol: "ETHPERP", type: "Perp", price: "1,860.5", change: "+0.75%", positive: true },
        { symbol: "SOLPERP", type: "Perp", price: "143.50", change: "+1.15%", positive: true },
        { symbol: "BNBPERP", type: "Perp", price: "592.00", change: "+1.08%", positive: true },
        { symbol: "XRPPERP", type: "Perp", price: "1.078", change: "+0.60%", positive: true },
        { symbol: "DOGEPERP", type: "Perp", price: "0.1025", change: "+1.45%", positive: true },
        { symbol: "AVAXPERP", type: "Perp", price: "24.90", change: "+3.45%", positive: true },
        { symbol: "SUIPERP", type: "Perp", price: "1.645", change: "+5.25%", positive: true },
      ],
    },
  },
};

export const MORE_MENU_DATA = {
  columns: [
    {
      id: "promotions",
      title: "Promotions",
      icon: GiftIcon,
      items: [
        {
          title: "Events Hub",
          description: "Big rewards and fresh events—no tricks, just perks. See what’s on now!",
          icon: GiftIcon,
          route: "/events",
        },
        {
          title: "Rewards Hub",
          description: "Check here often for new rewards and perks as you trade",
          icon: CoinsDollarIcon,
          route: "/rewards",
        },
        {
          title: "NexTradeX Anniversary",
          description: "Celebrate NexTradeX Anniversary — Share 650,000 USDT and Exclusive Rewards!",
          icon: StarsIcon,
          route: "/anniversary",
          badge: "HOT",
        },
        {
          title: "Referral Program",
          description: "Refer friends to earn a 35% commission",
          icon: UserGroupIcon,
          route: "/referral",
        },
        {
          title: "Affiliate Program",
          description: "Earn up to 60% commission as an agent, community leader, or KOL",
          icon: MoneyExchange01Icon,
          route: "/affiliate",
        },
        {
          title: "Live",
          description: "Apply and earn up to 70% commission",
          icon: Activity01Icon,
          route: "/live",
        },
      ],
    },
    {
      id: "information",
      title: "Information",
      icon: Book01Icon,
      items: [
        {
          title: "Square",
          description: "Discover trending community topics and KOL opportunities",
          icon: Activity01Icon,
          route: "/square",
        },
        {
          title: "NexTradeX Learn",
          description: "The best way to learn crypto and web3",
          icon: Book01Icon,
          route: "/learn",
        },
        {
          title: "Knowledge Base",
          description: "Get the clarity and data-driven insights you need to trade with confidence",
          icon: MarketAnalysisIcon,
          route: "/knowledge-base",
        },
        {
          title: "Announcements",
          description: "Important updates and official news from NexTradeX",
          icon: FlashIcon,
          route: "/announcements",
        },
        {
          title: "Blog",
          description: "The official blog for blockchain insights and analysis",
          icon: Book01Icon,
          route: "/blog",
        },
        {
          title: "News",
          description: "Stay informed with the latest headlines and crypto trends",
          icon: Globe02Icon,
          route: "/news",
        },
      ],
    },
    {
      id: "applications",
      title: "Applications",
      icon: Layers01Icon,
      items: [
        {
          title: "Trixie AI Assistant",
          description: "Your personal smart assistant",
          icon: BotIcon,
          route: "/trixie-explains",
          badge: "AI",
        },
        {
          title: "Community",
          description: "Share airdrops and trading strategies with the community",
          icon: UserGroupIcon,
          route: "/community",
        },
        {
          title: "Security",
          description: "Keep your assets safe with our protection tools",
          icon: Layers01Icon,
          route: "/security",
        },
      ],
    },
    {
      id: "others",
      title: "Others",
      icon: Globe02Icon,
      items: [
        {
          title: "Brand Partnerships",
          description: "Discover our partners",
          icon: Globe02Icon,
          route: "/partnerships",
        },
      ],
    },
  ],
};

export const MAIN_NAV_ITEMS = [
  { id: "dashboard", label: "Dashboard", type: "link", route: "/dashboard" },
  { id: "markets", label: "Markets", type: "link", route: "/markets" },
  { id: "trade", label: "Trade", type: "megamenu", data: TRADE_MENU_DATA },
  { id: "derivatives", label: "Derivatives", type: "megamenu", data: DERIVATIVES_MENU_DATA },
  { id: "wallets", label: "Wallets", type: "link", route: "/wallets" },
  { id: "docs", label: "Docs", type: "link", route: "/support" },
  { id: "more", label: "More", type: "megamenu", data: MORE_MENU_DATA },
];
